name: Build & Publish Extension
on:
  push:
    tags:
      - v*
  workflow_dispatch:
jobs:
  ut:
    runs-on: ubuntu-latest
    steps:
      - name: Setup pnpm
        uses: pnpm/action-setup@v4.1.0
        with:
          version: 10.12.3
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Install deps
        run: pnpm install
      - name: Run UT
        run: pnpm test
  build:
    runs-on: ubuntu-latest
    needs: ['ut']
    steps:
      - name: Setup pnpm
        uses: pnpm/action-setup@v4.1.0
        with:
          version: 10.12.3
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Install deps
        run: pnpm install
      - name: Build
        run: pnpm zip && pnpm zip:firefox
      - name: Upload
        uses: actions/upload-artifact@v4.6.2
        with:
          name: build-output
          path: |
            output/v2ex-stats-chrome-${{ github.ref_name }}.zip
            output/v2ex-stats-firefox-${{ github.ref_name }}.zip
            output/v2ex-stats-sources-${{ github.ref_name }}.zip
  release-chrome:
    runs-on: ubuntu-latest
    needs: ['build']
    steps:
      - name: Download
        uses: actions/download-artifact@v4.3.0
        with:
          name: build-output
      - name: Publish Chrome extension
        uses: mnao305/chrome-extension-upload@v5.0.0
        with:
          extension-id: kclaclglgljalkhaihmicdlcnaacpghp
          client-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          refresh-token: ${{ secrets.REFRESH_TOKEN }}
          file-path: v2ex-stats-chrome-${{ github.ref_name }}.zip
  release-github:
    runs-on: ubuntu-latest
    needs: ['build']
    permissions:
      contents: write
    steps:
      - name: Download
        uses: actions/download-artifact@v4.3.0
        with:
          name: build-output
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2.3.2
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            v2ex-stats-chrome-${{ github.ref_name }}.zip
            v2ex-stats-firefox-${{ github.ref_name }}.zip
            v2ex-stats-source-${{ github.ref_name }}.zip
  end:
    runs-on: ubuntu-latest
    needs: ['release-chrome', 'release-github']
    steps:
      - name: Finish
        run: echo Finish
        
        
          
        
      

        
            
